In [20]:
import pandas as pd
import numpy as np

In [21]:
m = pd.read_csv("D:/UIDAI HACKATHON/UIDAI-Hackathon/data/processed/monthly_pin_raw.csv")
m.head()

,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_
0,Maharashtra,Thane,400601,2025-03,0.0,0.0,0.0,99.0,1058.0,0.0,0.0
1,Maharashtra,Thane,400601,2025-04,0.0,0.0,0.0,104.0,783.0,393.0,831.0
2,Maharashtra,Thane,400601,2025-05,80.0,30.0,14.0,0.0,0.0,575.0,1122.0
3,Maharashtra,Thane,400601,2025-06,53.0,33.0,1.0,0.0,0.0,165.0,670.0
4,Maharashtra,Thane,400601,2025-07,0.0,0.0,0.0,0.0,0.0,407.0,912.0

# ICI (Identity Churn Index)
### ICI answers this question:
###  In this PIN, in this month, how much of Aadhaar activity is driven by adults repeatedly changing their identity details?

### Formula:
### 1) adult_changes (i.e total demographic and biometric updates made by adults)
### 2) total_transactions (all enrolments + all updates in that pincode)
### Hence ICI = adult_changes / total_transactions

### Conclusion:
###  Voluntary updates = stress / migration / instability

In [22]:
# computing new enrolments per month,  per PIN

m['new_enrol'] = (
    m['age_0_5'] +
    m['age_5_17'] +
    m['age_18_greater']
)

In [23]:
m.head(20)

,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,new_enrol
0,Maharashtra,Thane,400601,2025-03,0.0,0.0,0.0,99.0,1058.0,0.0,0.0,0.0
1,Maharashtra,Thane,400601,2025-04,0.0,0.0,0.0,104.0,783.0,393.0,831.0,0.0
2,Maharashtra,Thane,400601,2025-05,80.0,30.0,14.0,0.0,0.0,575.0,1122.0,124.0
3,Maharashtra,Thane,400601,2025-06,53.0,33.0,1.0,0.0,0.0,165.0,670.0,87.0
4,Maharashtra,Thane,400601,2025-07,0.0,0.0,0.0,0.0,0.0,407.0,912.0,0.0
5,Maharashtra,Thane,400601,2025-08,0.0,0.0,0.0,0.0,0.0,230.0,711.0,0.0
6,Maharashtra,Thane,400601,2025-09,155.0,66.0,3.0,79.0,831.0,704.0,979.0,224.0
7,Maharashtra,Thane,400601,2025-10,79.0,17.0,1.0,73.0,522.0,521.0,794.0,97.0
8,Maharashtra,Thane,400601,2025-11,194.0,20.0,2.0,125.0,1675.0,1096.0,1655.0,216.0
9,Maharashtra,Thane,400601,2025-12,78.0,11.0,2.0,129.0,1547.0,1240.0,1405.0,91.0
10,Maharashtra,Thane,400601,2026-01,25.0,6.0,2.0,7.0,84.0,83.0,127.0,33.0
11,Maharashtra,Thane,400602,2025-03,0.0,0.0,0.0,27.0,467.0,0.0,0.0,0.0
12,Maharashtra,Thane,400602,2025-04,0.0,0.0,0.0,0.0,0.0,107.0,254.0,0.0
13,Maharashtra,Thane,400602,2025-05,0.0,0.0,0.0,0.0,0.0,158.0,352.0,0.0
14,Maharashtra,Thane,400602,2025-06,9.0,6.0,0.0,0.0,0.0,63.0,215.0,15.0
15,Maharashtra,Thane,400602,2025-07,0.0,0.0,0.0,0.0,0.0,53.0,233.0,0.0
16,Maharashtra,Thane,400602,2025-08,0.0,0.0,0.0,0.0,0.0,99.0,247.0,0.0
17,Maharashtra,Thane,400602,2025-09,34.0,10.0,0.0,31.0,293.0,280.0,282.0,44.0
18,Maharashtra,Thane,400602,2025-10,16.0,4.0,0.0,13.0,176.0,142.0,235.0,20.0
19,Maharashtra,Thane,400602,2025-11,39.0,6.0,0.0,25.0,572.0,248.0,401.0,45.0

In [24]:
# computing total transactions per month, per PIN
m['total_txn'] = (
    m['new_enrol'] +
    m['demo_age_5_17'] +
    m['demo_age_17_'] +
    m['bio_age_5_17'] +
    m['bio_age_17_']
)

In [25]:
m.head(20)

,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,new_enrol,total_txn
0,Maharashtra,Thane,400601,2025-03,0.0,0.0,0.0,99.0,1058.0,0.0,0.0,0.0,1157.0
1,Maharashtra,Thane,400601,2025-04,0.0,0.0,0.0,104.0,783.0,393.0,831.0,0.0,2111.0
2,Maharashtra,Thane,400601,2025-05,80.0,30.0,14.0,0.0,0.0,575.0,1122.0,124.0,1821.0
3,Maharashtra,Thane,400601,2025-06,53.0,33.0,1.0,0.0,0.0,165.0,670.0,87.0,922.0
4,Maharashtra,Thane,400601,2025-07,0.0,0.0,0.0,0.0,0.0,407.0,912.0,0.0,1319.0
5,Maharashtra,Thane,400601,2025-08,0.0,0.0,0.0,0.0,0.0,230.0,711.0,0.0,941.0
6,Maharashtra,Thane,400601,2025-09,155.0,66.0,3.0,79.0,831.0,704.0,979.0,224.0,2817.0
7,Maharashtra,Thane,400601,2025-10,79.0,17.0,1.0,73.0,522.0,521.0,794.0,97.0,2007.0
8,Maharashtra,Thane,400601,2025-11,194.0,20.0,2.0,125.0,1675.0,1096.0,1655.0,216.0,4767.0
9,Maharashtra,Thane,400601,2025-12,78.0,11.0,2.0,129.0,1547.0,1240.0,1405.0,91.0,4412.0
10,Maharashtra,Thane,400601,2026-01,25.0,6.0,2.0,7.0,84.0,83.0,127.0,33.0,334.0
11,Maharashtra,Thane,400602,2025-03,0.0,0.0,0.0,27.0,467.0,0.0,0.0,0.0,494.0
12,Maharashtra,Thane,400602,2025-04,0.0,0.0,0.0,0.0,0.0,107.0,254.0,0.0,361.0
13,Maharashtra,Thane,400602,2025-05,0.0,0.0,0.0,0.0,0.0,158.0,352.0,0.0,510.0
14,Maharashtra,Thane,400602,2025-06,9.0,6.0,0.0,0.0,0.0,63.0,215.0,15.0,293.0
15,Maharashtra,Thane,400602,2025-07,0.0,0.0,0.0,0.0,0.0,53.0,233.0,0.0,286.0
16,Maharashtra,Thane,400602,2025-08,0.0,0.0,0.0,0.0,0.0,99.0,247.0,0.0,346.0
17,Maharashtra,Thane,400602,2025-09,34.0,10.0,0.0,31.0,293.0,280.0,282.0,44.0,930.0
18,Maharashtra,Thane,400602,2025-10,16.0,4.0,0.0,13.0,176.0,142.0,235.0,20.0,586.0
19,Maharashtra,Thane,400602,2025-11,39.0,6.0,0.0,25.0,572.0,248.0,401.0,45.0,1291.0

In [26]:
# computing ICI 
# 1 is put here to avoid denominator being 0 

m['ICI'] = (m['demo_age_17_'] + m['bio_age_17_']) / (m['total_txn'] + 1)

In [27]:
m.head(10)

,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,new_enrol,total_txn,ICI
0,Maharashtra,Thane,400601,2025-03,0.0,0.0,0.0,99.0,1058.0,0.0,0.0,0.0,1157.0,0.913644
1,Maharashtra,Thane,400601,2025-04,0.0,0.0,0.0,104.0,783.0,393.0,831.0,0.0,2111.0,0.764205
2,Maharashtra,Thane,400601,2025-05,80.0,30.0,14.0,0.0,0.0,575.0,1122.0,124.0,1821.0,0.615807
3,Maharashtra,Thane,400601,2025-06,53.0,33.0,1.0,0.0,0.0,165.0,670.0,87.0,922.0,0.725894
4,Maharashtra,Thane,400601,2025-07,0.0,0.0,0.0,0.0,0.0,407.0,912.0,0.0,1319.0,0.690909
5,Maharashtra,Thane,400601,2025-08,0.0,0.0,0.0,0.0,0.0,230.0,711.0,0.0,941.0,0.754777
6,Maharashtra,Thane,400601,2025-09,155.0,66.0,3.0,79.0,831.0,704.0,979.0,224.0,2817.0,0.642300
7,Maharashtra,Thane,400601,2025-10,79.0,17.0,1.0,73.0,522.0,521.0,794.0,97.0,2007.0,0.655378
8,Maharashtra,Thane,400601,2025-11,194.0,20.0,2.0,125.0,1675.0,1096.0,1655.0,216.0,4767.0,0.698406
9,Maharashtra,Thane,400601,2025-12,78.0,11.0,2.0,129.0,1547.0,1240.0,1405.0,91.0,4412.0,0.668933

In [28]:
m["ICI"].describe()

count    982.000000
mean       0.780689
std        0.135276
min        0.423529
25%        0.678684
50%        0.769536
75%        0.909091
max        0.995708
Name: ICI, dtype: float64

In [29]:
m[['pincode','month','demo_age_17_','bio_age_17_','total_txn','ICI']].head(10)

   pincode    month  demo_age_17_  bio_age_17_  total_txn       ICI
0   400601  2025-03        1058.0          0.0     1157.0  0.913644
1   400601  2025-04         783.0        831.0     2111.0  0.764205
2   400601  2025-05           0.0       1122.0     1821.0  0.615807
3   400601  2025-06           0.0        670.0      922.0  0.725894
4   400601  2025-07           0.0        912.0     1319.0  0.690909
5   400601  2025-08           0.0        711.0      941.0  0.754777
6   400601  2025-09         831.0        979.0     2817.0  0.642300
7   400601  2025-10         522.0        794.0     2007.0  0.655378
8   400601  2025-11        1675.0       1655.0     4767.0  0.698406
9   400601  2025-12        1547.0       1405.0     4412.0  0.668933

In [30]:
m['ICI'].describe(percentiles=[0.1,0.25,0.5,0.75,0.9,0.95])

count    982.000000
mean       0.780689
std        0.135276
min        0.423529
10%        0.604033
25%        0.678684
50%        0.769536
75%        0.909091
90%        0.957426
95%        0.974359
max        0.995708
Name: ICI, dtype: float64

In [31]:
m["ICI"].sort_values(ascending=False)

528    0.995708
612    0.993631
437    0.993421
532    0.992966
550    0.992914
         ...
197    0.452174
147    0.443038
878    0.442727
134    0.437822
900    0.423529
Name: ICI, Length: 982, dtype: float64

### Analysis of results

In [32]:
# creating threshold values 

ici_90 = m['ICI'].quantile(0.90)
ici_75 = m['ICI'].quantile(0.75)

ici_90, ici_75

(0.9574258118701008, 0.9090909090909091)

In [33]:
m.head()

,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,new_enrol,total_txn,ICI
0,Maharashtra,Thane,400601,2025-03,0.0,0.0,0.0,99.0,1058.0,0.0,0.0,0.0,1157.0,0.913644
1,Maharashtra,Thane,400601,2025-04,0.0,0.0,0.0,104.0,783.0,393.0,831.0,0.0,2111.0,0.764205
2,Maharashtra,Thane,400601,2025-05,80.0,30.0,14.0,0.0,0.0,575.0,1122.0,124.0,1821.0,0.615807
3,Maharashtra,Thane,400601,2025-06,53.0,33.0,1.0,0.0,0.0,165.0,670.0,87.0,922.0,0.725894
4,Maharashtra,Thane,400601,2025-07,0.0,0.0,0.0,0.0,0.0,407.0,912.0,0.0,1319.0,0.690909

In [34]:
# Flag PIN-MONTHS
m['ici_top_10pct'] = m['ICI'] >= ici_90
m['ici_top_25pct'] = m['ICI'] >= ici_75

In [35]:
m[['pincode', 'month', 'ICI', 'ici_top_10pct', 'ici_top_25pct']].head()

   pincode    month       ICI  ici_top_10pct  ici_top_25pct
0   400601  2025-03  0.913644          False           True
1   400601  2025-04  0.764205          False          False
2   400601  2025-05  0.615807          False          False
3   400601  2025-06  0.725894          False          False
4   400601  2025-07  0.690909          False          False

In [36]:
m["ici_top_10pct"].value_counts()

ici_top_10pct
False    883
True      99
Name: count, dtype: int64

In [37]:
m["ici_top_25pct"].value_counts()

ici_top_25pct
False    735
True     247
Name: count, dtype: int64

### Aggregating PIN codes which have higher ICI more frequently is much better than just providing which PIN codes have a higher ICI value.

In [38]:
# count how often each PIN appears in top 10 percent 

pin_ici_freq = (
    m.groupby('pincode')
     .agg(
         months_total=('month', 'nunique'),
         top10_count=('ici_top_10pct', 'sum'),
         top25_count=('ici_top_25pct', 'sum')
     )
     .reset_index()
)

pin_ici_freq.head(30)

    pincode  months_total  top10_count  top25_count
0    400601            11            0            1
1    400602            11            0            1
2    400603            11            0            0
3    400604            11            0            0
4    400605            11            0            0
5    400606            11            0            0
6    400607            11            0            0
7    400608            11            0            0
8    400610            11            0            0
9    400612            11            0            0
10   400614            11            0            0
11   400615            11            0            0
12   400701            10            0            0
13   400703            10            0            0
14   400705            11            0            0
15   400706            11            0            0
16   400708            11            0            0
17   400709            11            0            1
18   400710            10            0            0
19   401101            11            0            0
20   401102            10            2            9
21   401103             9            6            8
22   401104             9            0            6
23   401105            11            0            1
24   401106            11            0            0
25   401107            11            0            1
26   401201            11            1            5
27   401202            11            3            7
28   401203            11            0            1
29   401204            10            0            0

In [39]:
# Counts alone are misleading if PINs have different data lengths. Hence we compute frequency

pin_ici_freq['top10_frac'] = (
    pin_ici_freq['top10_count'] / pin_ici_freq['months_total']
)

pin_ici_freq['top25_frac'] = (
    pin_ici_freq['top25_count'] / pin_ici_freq['months_total']
)

In [40]:
pin_ici_freq

    pincode  months_total  top10_count  top25_count  top10_frac  top25_frac
0    400601            11            0            1    0.000000    0.090909
1    400602            11            0            1    0.000000    0.090909
2    400603            11            0            0    0.000000    0.000000
3    400604            11            0            0    0.000000    0.000000
4    400605            11            0            0    0.000000    0.000000
..      ...           ...          ...          ...         ...         ...
91   421601            11            0            0    0.000000    0.000000
92   421602            11            0            0    0.000000    0.000000
93   421603            11            0            0    0.000000    0.000000
94   421604             9            3            9    0.333333    1.000000
95   421605            11            0            1    0.000000    0.090909

[96 rows x 6 columns]

In [41]:
# Top persistent extreme churn PINs

pin_ici_freq.sort_values(
    'top10_frac',
    ascending=False
).head(10)

    pincode  months_total  top10_count  top25_count  top10_frac  top25_frac
60   401702             9            6            8    0.666667    0.888889
21   401103             9            6            8    0.666667    0.888889
53   401605             9            6            8    0.666667    0.888889
51   401603             9            6            7    0.666667    0.777778
41   401403             9            6            9    0.666667    1.000000
46   401503             9            5            8    0.555556    0.888889
44   401501            11            5            7    0.454545    0.636364
59   401701             9            4            6    0.444444    0.666667
43   401405             9            4            6    0.444444    0.666667
76   421303             9            4            6    0.444444    0.666667

# BDR (Biometric Distress Ratio)

### BDR answers this question

### When adults update Aadhaar in this PIN and month, how much of that updating is driven by biometric problems rather than normal demographic changes?

### Why BDR complements ICI (important)

### High ICI + High BDR → biometric distress zone

### High ICI + Low BDR → migration / address churn

### Low ICI + High BDR → isolated biometric problems

# Formula:

### 1) adult biometric updates (total biometric updates made by adults)
### 2) adult demographic updates (total demographic updates made by adults)

### Hence,
### BDR = adult biometric updates / (adult demographic updates + 1)

# Conclusion:

### So BDR tells us: Is biometric failure dominating adult updates here?

In [43]:
# computing BDR 
m['BDR'] = m['bio_age_17_'] / (m['demo_age_17_'] + 1)

In [44]:
m.head()

,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,new_enrol,total_txn,ICI,ici_top_10pct,ici_top_25pct,BDR
0,Maharashtra,Thane,400601,2025-03,0.0,0.0,0.0,99.0,1058.0,0.0,0.0,0.0,1157.0,0.913644,False,True,0.000000
1,Maharashtra,Thane,400601,2025-04,0.0,0.0,0.0,104.0,783.0,393.0,831.0,0.0,2111.0,0.764205,False,False,1.059949
2,Maharashtra,Thane,400601,2025-05,80.0,30.0,14.0,0.0,0.0,575.0,1122.0,124.0,1821.0,0.615807,False,False,1122.000000
3,Maharashtra,Thane,400601,2025-06,53.0,33.0,1.0,0.0,0.0,165.0,670.0,87.0,922.0,0.725894,False,False,670.000000
4,Maharashtra,Thane,400601,2025-07,0.0,0.0,0.0,0.0,0.0,407.0,912.0,0.0,1319.0,0.690909,False,False,912.000000

In [45]:
# Sanity Check

m['BDR'].describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9, 0.95])

count     982.000000
mean      187.852228
std       402.748166
min         0.000000
10%         0.522358
25%         0.855247
50%         1.806004
75%       200.000000
90%       643.800000
95%       918.800000
max      4755.000000
Name: BDR, dtype: float64

In [47]:

m[['pincode','month','bio_age_17_','demo_age_17_','BDR']].head(10)

   pincode    month  bio_age_17_  demo_age_17_          BDR
0   400601  2025-03          0.0        1058.0     0.000000
1   400601  2025-04        831.0         783.0     1.059949
2   400601  2025-05       1122.0           0.0  1122.000000
3   400601  2025-06        670.0           0.0   670.000000
4   400601  2025-07        912.0           0.0   912.000000
5   400601  2025-08        711.0           0.0   711.000000
6   400601  2025-09        979.0         831.0     1.176683
7   400601  2025-10        794.0         522.0     1.518164
8   400601  2025-11       1655.0        1675.0     0.987470
9   400601  2025-12       1405.0        1547.0     0.907623

In [49]:
# FLAG the rows where there are 0 demographic updates and only biometric updates 
m['biometric_only'] = m['demo_age_17_'] == 0

In [50]:
m.head()

,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,new_enrol,total_txn,ICI,ici_top_10pct,ici_top_25pct,BDR,biometric_only
0,Maharashtra,Thane,400601,2025-03,0.0,0.0,0.0,99.0,1058.0,0.0,0.0,0.0,1157.0,0.913644,False,True,0.000000,False
1,Maharashtra,Thane,400601,2025-04,0.0,0.0,0.0,104.0,783.0,393.0,831.0,0.0,2111.0,0.764205,False,False,1.059949,False
2,Maharashtra,Thane,400601,2025-05,80.0,30.0,14.0,0.0,0.0,575.0,1122.0,124.0,1821.0,0.615807,False,False,1122.000000,True
3,Maharashtra,Thane,400601,2025-06,53.0,33.0,1.0,0.0,0.0,165.0,670.0,87.0,922.0,0.725894,False,False,670.000000,True
4,Maharashtra,Thane,400601,2025-07,0.0,0.0,0.0,0.0,0.0,407.0,912.0,0.0,1319.0,0.690909,False,False,912.000000,True

In [52]:
# computing BDR only for the rows having some demographic updates as well and keeping empty values in rows having no demographic updates 

m['BDR_valid'] = None
mask = m['demo_age_17_'] > 0
m.loc[mask, 'BDR_valid'] = m.loc[mask, 'bio_age_17_'] / m.loc[mask, 'demo_age_17_']

In [58]:
m.head()

,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,new_enrol,total_txn,ICI,ici_top_10pct,ici_top_25pct,BDR,biometric_only,BDR_valid
0,Maharashtra,Thane,400601,2025-03,0.0,0.0,0.0,99.0,1058.0,0.0,0.0,0.0,1157.0,0.913644,False,True,0.000000,False,0.0
1,Maharashtra,Thane,400601,2025-04,0.0,0.0,0.0,104.0,783.0,393.0,831.0,0.0,2111.0,0.764205,False,False,1.059949,False,1.061303
2,Maharashtra,Thane,400601,2025-05,80.0,30.0,14.0,0.0,0.0,575.0,1122.0,124.0,1821.0,0.615807,False,False,1122.000000,True,None
3,Maharashtra,Thane,400601,2025-06,53.0,33.0,1.0,0.0,0.0,165.0,670.0,87.0,922.0,0.725894,False,False,670.000000,True,None
4,Maharashtra,Thane,400601,2025-07,0.0,0.0,0.0,0.0,0.0,407.0,912.0,0.0,1319.0,0.690909,False,False,912.000000,True,None

In [59]:
cap = m['BDR_valid'].quantile(0.95)
cap

2.7296969696969695

In [60]:
m['BDR_capped'] = m['BDR_valid'].clip(upper=cap)

In [61]:
m.head()

,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,bio_age_17_,new_enrol,total_txn,ICI,ici_top_10pct,ici_top_25pct,BDR,biometric_only,BDR_valid,BDR_capped
0,Maharashtra,Thane,400601,2025-03,0.0,0.0,0.0,99.0,1058.0,0.0,0.0,0.0,1157.0,0.913644,False,True,0.000000,False,0.0,0.0
1,Maharashtra,Thane,400601,2025-04,0.0,0.0,0.0,104.0,783.0,393.0,831.0,0.0,2111.0,0.764205,False,False,1.059949,False,1.061303,1.061303
2,Maharashtra,Thane,400601,2025-05,80.0,30.0,14.0,0.0,0.0,575.0,1122.0,124.0,1821.0,0.615807,False,False,1122.000000,True,None,None
3,Maharashtra,Thane,400601,2025-06,53.0,33.0,1.0,0.0,0.0,165.0,670.0,87.0,922.0,0.725894,False,False,670.000000,True,None,None
4,Maharashtra,Thane,400601,2025-07,0.0,0.0,0.0,0.0,0.0,407.0,912.0,0.0,1319.0,0.690909,False,False,912.000000,True,None,None

In [65]:
# tells us how many months each pin had where there were only and only biometric updates
bd_pin = (
    m.groupby('pincode')
     .agg(
         months_total=('month', 'nunique'),
         biometric_only_count=('biometric_only', 'sum')
     )
     .reset_index()
)

bd_pin.head()

   pincode  months_total  biometric_only_count
0   400601            11                     4
1   400602            11                     5
2   400603            11                     5
3   400604            11                     5
4   400605            11                     4

In [66]:
# convert into frequency or fraction due to data length inconcisitency

bd_pin['biometric_only_fraction'] = (
    bd_pin['biometric_only_count'] / bd_pin['months_total']
)

In [67]:
bd_pin.head(20)

    pincode  months_total  biometric_only_count  biometric_only_fraction
0    400601            11                     4                 0.363636
1    400602            11                     5                 0.454545
2    400603            11                     5                 0.454545
3    400604            11                     5                 0.454545
4    400605            11                     4                 0.363636
5    400606            11                     4                 0.363636
6    400607            11                     4                 0.363636
7    400608            11                     5                 0.454545
8    400610            11                     5                 0.454545
9    400612            11                     1                 0.090909
10   400614            11                     5                 0.454545
11   400615            11                     5                 0.454545
12   400701            10                     4                 0.400000
13   400703            10                     4                 0.400000
14   400705            11                     5                 0.454545
15   400706            11                     3                 0.272727
16   400708            11                     4                 0.363636
17   400709            11                     5                 0.454545
18   400710            10                     5                 0.500000
19   401101            11                     5                 0.454545

In [71]:
# tells when demographic updates DID happen, how strong was biometric pressure

bd_stats = (
    m.groupby('pincode')
     .agg(
         median_BDR=('BDR_capped', 'median'),
         mean_BDR=('BDR_capped', 'mean')
     )
     .reset_index()
)

bd_stats.head(20)

    pincode median_BDR  mean_BDR
0    400601   1.061303  1.024093
1    400602   0.892646  0.821139
2    400603   1.674895   1.81907
3    400604   1.262306  1.307597
4    400605   1.011805  1.026834
5    400606   1.295176  1.526119
6    400607   0.537838  0.722305
7    400608   0.510002  0.540892
8    400610   0.743746  0.858524
9    400612   0.722647  0.894386
10   400614   0.586188   0.67655
11   400615   0.640322  0.766315
12   400701   0.930179  1.053721
13   400703   0.820853   0.96321
14   400705   0.638342  0.788006
15   400706   0.556724  0.688853
16   400708   0.852036  0.988027
17   400709   1.079706  0.934034
18   400710   1.333333  1.255181
19   401101   1.334336  1.251705

In [72]:
# combining the "biometrics_only" data with the normal bdr values

bd_pin = bd_pin.merge(bd_stats, on='pincode', how='left')

In [73]:
bd_pin.head(20)

,pincode,months_total,biometric_only_count,biometric_only_fraction,median_BDR,mean_BDR
0,400601,11,4,0.363636,1.061303,1.024093
1,400602,11,5,0.454545,0.892646,0.821139
2,400603,11,5,0.454545,1.674895,1.81907
3,400604,11,5,0.454545,1.262306,1.307597
4,400605,11,4,0.363636,1.011805,1.026834
5,400606,11,4,0.363636,1.295176,1.526119
6,400607,11,4,0.363636,0.537838,0.722305
7,400608,11,5,0.454545,0.510002,0.540892
8,400610,11,5,0.454545,0.743746,0.858524
9,400612,11,1,0.090909,0.722647,0.894386
10,400614,11,5,0.454545,0.586188,0.67655
11,400615,11,5,0.454545,0.640322,0.766315
12,400701,10,4,0.400000,0.930179,1.053721
13,400703,10,4,0.400000,0.820853,0.96321
14,400705,11,5,0.454545,0.638342,0.788006
15,400706,11,3,0.272727,0.556724,0.688853
16,400708,11,4,0.363636,0.852036,0.988027
17,400709,11,5,0.454545,1.079706,0.934034
18,400710,10,5,0.500000,1.333333,1.255181
19,401101,11,5,0.454545,1.334336,1.251705

In [74]:
bd_pin.describe()

,pincode,months_total,biometric_only_count,biometric_only_fraction
count,96.000000,96.000000,96.000000,96.000000
mean,408296.093750,10.229167,4.468750,0.439722
std,9695.159269,1.010254,1.045825,0.100375
min,400601.000000,6.000000,1.000000,0.090909
25%,401105.750000,9.000000,4.000000,0.444444
50%,401505.000000,11.000000,5.000000,0.454545
75%,421202.250000,11.000000,5.000000,0.454545
max,421605.000000,11.000000,6.000000,0.714286

In [76]:
print(bd_pin['biometric_only_fraction'].quantile(0.75))
print(bd_pin['median_BDR'].quantile(0.75))

0.45454545454545453
1.2775756090773243

In [75]:
# finding the pins which are much worse than others 

bd_pin['high_biometric_only'] = (
    bd_pin['biometric_only_fraction'] >=
    bd_pin['biometric_only_fraction'].quantile(0.75)
)

bd_pin['high_BDR'] = (
    bd_pin['median_BDR'] >=
    bd_pin['median_BDR'].quantile(0.75)
)

In [77]:
bd_pin.head(20)

,pincode,months_total,biometric_only_count,biometric_only_fraction,median_BDR,mean_BDR,high_biometric_only,high_BDR
0,400601,11,4,0.363636,1.061303,1.024093,False,False
1,400602,11,5,0.454545,0.892646,0.821139,True,False
2,400603,11,5,0.454545,1.674895,1.81907,True,True
3,400604,11,5,0.454545,1.262306,1.307597,True,False
4,400605,11,4,0.363636,1.011805,1.026834,False,False
5,400606,11,4,0.363636,1.295176,1.526119,False,True
6,400607,11,4,0.363636,0.537838,0.722305,False,False
7,400608,11,5,0.454545,0.510002,0.540892,True,False
8,400610,11,5,0.454545,0.743746,0.858524,True,False
9,400612,11,1,0.090909,0.722647,0.894386,False,False
10,400614,11,5,0.454545,0.586188,0.67655,True,False
11,400615,11,5,0.454545,0.640322,0.766315,True,False
12,400701,10,4,0.400000,0.930179,1.053721,False,False
13,400703,10,4,0.400000,0.820853,0.96321,False,False
14,400705,11,5,0.454545,0.638342,0.788006,True,False
15,400706,11,3,0.272727,0.556724,0.688853,False,False
16,400708,11,4,0.363636,0.852036,0.988027,False,False
17,400709,11,5,0.454545,1.079706,0.934034,True,False
18,400710,10,5,0.500000,1.333333,1.255181,True,True
19,401101,11,5,0.454545,1.334336,1.251705,True,True

In [78]:
# combining the pin-month data together 

pin_summary = pin_ici_freq.merge(
    bd_pin,
    on='pincode',
    how='left'
)

In [80]:
pin_summary.head(30)

,pincode,months_total_x,top10_count,top25_count,top10_frac,top25_frac,months_total_y,biometric_only_count,biometric_only_fraction,median_BDR,mean_BDR,high_biometric_only,high_BDR
0,400601,11,0,1,0.000000,0.090909,11,4,0.363636,1.061303,1.024093,False,False
1,400602,11,0,1,0.000000,0.090909,11,5,0.454545,0.892646,0.821139,True,False
2,400603,11,0,0,0.000000,0.000000,11,5,0.454545,1.674895,1.81907,True,True
3,400604,11,0,0,0.000000,0.000000,11,5,0.454545,1.262306,1.307597,True,False
4,400605,11,0,0,0.000000,0.000000,11,4,0.363636,1.011805,1.026834,False,False
5,400606,11,0,0,0.000000,0.000000,11,4,0.363636,1.295176,1.526119,False,True
6,400607,11,0,0,0.000000,0.000000,11,4,0.363636,0.537838,0.722305,False,False
7,400608,11,0,0,0.000000,0.000000,11,5,0.454545,0.510002,0.540892,True,False
8,400610,11,0,0,0.000000,0.000000,11,5,0.454545,0.743746,0.858524,True,False
9,400612,11,0,0,0.000000,0.000000,11,1,0.090909,0.722647,0.894386,False,False
10,400614,11,0,0,0.000000,0.000000,11,5,0.454545,0.586188,0.67655,True,False
11,400615,11,0,0,0.000000,0.000000,11,5,0.454545,0.640322,0.766315,True,False
12,400701,10,0,0,0.000000,0.000000,10,4,0.400000,0.930179,1.053721,False,False
13,400703,10,0,0,0.000000,0.000000,10,4,0.400000,0.820853,0.96321,False,False
14,400705,11,0,0,0.000000,0.000000,11,5,0.454545,0.638342,0.788006,True,False
15,400706,11,0,0,0.000000,0.000000,11,3,0.272727,0.556724,0.688853,False,False
16,400708,11,0,0,0.000000,0.000000,11,4,0.363636,0.852036,0.988027,False,False
17,400709,11,0,1,0.000000,0.090909,11,5,0.454545,1.079706,0.934034,True,False
18,400710,10,0,0,0.000000,0.000000,10,5,0.500000,1.333333,1.255181,True,True
19,401101,11,0,0,0.000000,0.000000,11,5,0.454545,1.334336,1.251705,True,True
20,401102,10,2,9,0.200000,0.900000,10,5,0.500000,1.540984,1.799482,True,True
21,401103,9,6,8,0.666667,0.888889,9,4,0.444444,1.978261,1.767311,False,True
22,401104,9,0,6,0.000000,0.666667,9,4,0.444444,2.0,1.912202,False,True
23,401105,11,0,1,0.000000,0.090909,11,5,0.454545,0.825705,0.854061,True,False
24,401106,11,0,0,0.000000,0.000000,11,5,0.454545,0.807188,0.935866,True,False
25,401107,11,0,1,0.000000,0.090909,11,1,0.090909,0.516314,0.514688,False,False
26,401201,11,1,5,0.090909,0.454545,11,6,0.545455,1.333333,1.405442,True,True
27,401202,11,3,7,0.272727,0.636364,11,6,0.545455,0.765957,0.926944,True,False
28,401203,11,0,1,0.000000,0.090909,11,6,0.545455,1.628692,1.713525,True,True
29,401204,10,0,0,0.000000,0.000000,10,5,0.500000,1.018433,1.228327,True,False

In [ ]:
pin_summary.shape

(96, 13)

# CBCR (Child Biometric Compliance Ratio)

### What CBCR answers (in plain words):
### When children come for Aadhaar updates in a PIN and month, are they actually completing the mandatory biometric update?

# Formula:

### 1) child biometric updates (total biometric updates of children)
### 2) child demographich updates (total demographic updates of children)

### Hence,
### CBCR = child biometric updates / (child biometric updates + child demographic updates + 1)

In [82]:
# computing the CBCR 

m['CBCR'] = (
    m['bio_age_5_17'] /
    (m['bio_age_5_17'] + m['demo_age_5_17'] + 1)
)

In [84]:
m.head(50)

,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,...,new_enrol,total_txn,ICI,ici_top_10pct,ici_top_25pct,BDR,biometric_only,BDR_valid,BDR_capped,CBCR
0,Maharashtra,Thane,400601,2025-03,0.0,0.0,0.0,99.0,1058.0,0.0,...,0.0,1157.0,0.913644,False,True,0.000000,False,0.0,0.0,0.000000
1,Maharashtra,Thane,400601,2025-04,0.0,0.0,0.0,104.0,783.0,393.0,...,0.0,2111.0,0.764205,False,False,1.059949,False,1.061303,1.061303,0.789157
2,Maharashtra,Thane,400601,2025-05,80.0,30.0,14.0,0.0,0.0,575.0,...,124.0,1821.0,0.615807,False,False,1122.000000,True,None,None,0.998264
3,Maharashtra,Thane,400601,2025-06,53.0,33.0,1.0,0.0,0.0,165.0,...,87.0,922.0,0.725894,False,False,670.000000,True,None,None,0.993976
4,Maharashtra,Thane,400601,2025-07,0.0,0.0,0.0,0.0,0.0,407.0,...,0.0,1319.0,0.690909,False,False,912.000000,True,None,None,0.997549
5,Maharashtra,Thane,400601,2025-08,0.0,0.0,0.0,0.0,0.0,230.0,...,0.0,941.0,0.754777,False,False,711.000000,True,None,None,0.995671
6,Maharashtra,Thane,400601,2025-09,155.0,66.0,3.0,79.0,831.0,704.0,...,224.0,2817.0,0.642300,False,False,1.176683,False,1.178099,1.178099,0.897959
7,Maharashtra,Thane,400601,2025-10,79.0,17.0,1.0,73.0,522.0,521.0,...,97.0,2007.0,0.655378,False,False,1.518164,False,1.521073,1.521073,0.875630
8,Maharashtra,Thane,400601,2025-11,194.0,20.0,2.0,125.0,1675.0,1096.0,...,216.0,4767.0,0.698406,False,False,0.987470,False,0.98806,0.98806,0.896890
9,Maharashtra,Thane,400601,2025-12,78.0,11.0,2.0,129.0,1547.0,1240.0,...,91.0,4412.0,0.668933,False,False,0.907623,False,0.908209,0.908209,0.905109
10,Maharashtra,Thane,400601,2026-01,25.0,6.0,2.0,7.0,84.0,83.0,...,33.0,334.0,0.629851,False,False,1.494118,False,1.511905,1.511905,0.912088
11,Maharashtra,Thane,400602,2025-03,0.0,0.0,0.0,27.0,467.0,0.0,...,0.0,494.0,0.943434,False,True,0.000000,False,0.0,0.0,0.000000
12,Maharashtra,Thane,400602,2025-04,0.0,0.0,0.0,0.0,0.0,107.0,...,0.0,361.0,0.701657,False,False,254.000000,True,None,None,0.990741
13,Maharashtra,Thane,400602,2025-05,0.0,0.0,0.0,0.0,0.0,158.0,...,0.0,510.0,0.688845,False,False,352.000000,True,None,None,0.993711
14,Maharashtra,Thane,400602,2025-06,9.0,6.0,0.0,0.0,0.0,63.0,...,15.0,293.0,0.731293,False,False,215.000000,True,None,None,0.984375
15,Maharashtra,Thane,400602,2025-07,0.0,0.0,0.0,0.0,0.0,53.0,...,0.0,286.0,0.811847,False,False,233.000000,True,None,None,0.981481
16,Maharashtra,Thane,400602,2025-08,0.0,0.0,0.0,0.0,0.0,99.0,...,0.0,346.0,0.711816,False,False,247.000000,True,None,None,0.990000
17,Maharashtra,Thane,400602,2025-09,34.0,10.0,0.0,31.0,293.0,280.0,...,44.0,930.0,0.617615,False,False,0.959184,False,0.962457,0.962457,0.897436
18,Maharashtra,Thane,400602,2025-10,16.0,4.0,0.0,13.0,176.0,142.0,...,20.0,586.0,0.700170,False,False,1.327684,False,1.335227,1.335227,0.910256
19,Maharashtra,Thane,400602,2025-11,39.0,6.0,0.0,25.0,572.0,248.0,...,45.0,1291.0,0.753096,False,False,0.699825,False,0.701049,0.701049,0.905109
20,Maharashtra,Thane,400602,2025-12,28.0,0.0,14.0,21.0,508.0,269.0,...,42.0,1258.0,0.735504,False,False,0.821218,False,0.822835,0.822835,0.924399
21,Maharashtra,Thane,400602,2026-01,6.0,0.0,2.0,3.0,38.0,44.0,...,8.0,135.0,0.588235,False,False,1.076923,False,1.105263,1.105263,0.916667
22,Maharashtra,Thane,400603,2025-03,0.0,0.0,0.0,30.0,508.0,168.0,...,0.0,1270.0,0.843430,False,False,1.108055,False,1.110236,1.110236,0.844221
23,Maharashtra,Thane,400603,2025-04,0.0,0.0,0.0,0.0,0.0,133.0,...,0.0,423.0,0.683962,False,False,290.000000,True,None,None,0.992537
24,Maharashtra,Thane,400603,2025-05,0.0,0.0,0.0,0.0,0.0,368.0,...,0.0,1115.0,0.669355,False,False,747.000000,True,None,None,0.997290
25,Maharashtra,Thane,400603,2025-06,17.0,10.0,1.0,0.0,0.0,84.0,...,28.0,396.0,0.715365,False,False,284.000000,True,None,None,0.988235
26,Maharashtra,Thane,400603,2025-07,0.0,0.0,0.0,0.0,0.0,101.0,...,0.0,401.0,0.746269,False,False,300.000000,True,None,None,0.990196
27,Maharashtra,Thane,400603,2025-08,0.0,0.0,0.0,0.0,0.0,46.0,...,0.0,169.0,0.723529,False,False,123.000000,True,None,None,0.978723
28,Maharashtra,Thane,400603,2025-09,27.0,15.0,0.0,15.0,213.0,370.0,...,42.0,1051.0,0.593156,False,False,1.920561,False,1.929577,1.929577,0.958549
29,Maharashtra,Thane,400603,2025-10,26.0,2.0,0.0,9.0,109.0,212.0,...,28.0,689.0,0.637681,False,False,3.009091,False,3.036697,2.729697,0.954955
30,Maharashtra,Thane,400603,2025-11,25.0,5.0,0.0,20.0,376.0,208.0,...,30.0,1168.0,0.778443,False,False,1.416446,False,1.420213,1.420213,0.908297
31,Maharashtra,Thane,400603,2025-12,16.0,6.0,0.0,23.0,400.0,226.0,...,22.0,1069.0,0.745794,False,False,0.992519,False,0.995,0.995,0.904000
32,Maharashtra,Thane,400603,2026-01,1.0,0.0,2.0,0.0,15.0,29.0,...,3.0,88.0,0.629213,False,False,2.562500,False,2.733333,2.729697,0.966667
33,Maharashtra,Thane,400604,2025-03,0.0,0.0,0.0,156.0,1503.0,513.0,...,0.0,3576.0,0.812692,False,False,0.933511,False,0.934132,0.934132,0.765672
34,Maharashtra,Thane,400604,2025-04,0.0,0.0,0.0,0.0,0.0,583.0,...,0.0,1653.0,0.646917,False,False,1070.000000,True,None,None,0.998288
35,Maharashtra,Thane,400604,2025-05,0.0,0.0,0.0,0.0,0.0,757.0,...,0.0,2524.0,0.699802,False,False,1767.000000,True,None,None,0.998681
36,Maharashtra,Thane,400604,2025-06,353.0,263.0,22.0,0.0,0.0,586.0,...,638.0,2640.0,0.536161,False,False,1416.000000,True,None,None,0.998296
37,Maharashtra,Thane,400604,2025-07,0.0,0.0,0.0,0.0,0.0,533.0,...,0.0,2050.0,0.739639,False,False,1517.000000,True,None,None,0.998127
38,Maharashtra,Thane,400604,2025-08,0.0,0.0,0.0,0.0,0.0,485.0,...,0.0,1627.0,0.701474,False,False,1142.000000,True,None,None,0.997942
39,Maharashtra,Thane,400604,2025-09,148.0,64.0,0.0,107.0,693.0,1364.0,...,212.0,3286.0,0.487679,False,False,1.311239,False,1.313131,1.313131,0.926630
40,Maharashtra,Thane,400604,2025-10,116.0,27.0,1.0,87.0,705.0,1273.0,...,144.0,3841.0,0.608277,False,False,2.311615,False,2.314894,2.314894,0.935342
41,Maharashtra,Thane,400604,2025-11,232.0,72.0,1.0,164.0,2202.0,1905.0,...,305.0,7568.0,0.686220,False,False,1.358148,False,1.358765,1.358765,0.920290
42,Maharashtra,Thane,400604,2025-12,117.0,18.0,37.0,169.0,2317.0,2019.0,...,172.0,7484.0,0.684569,False,False,1.210958,False,1.21148,1.21148,0.922339
43,Maharashtra,Thane,400604,2026-01,23.0,4.0,0.0,22.0,129.0,59.0,...,27.0,329.0,0.669697,False,False,0.707692,False,0.713178,0.713178,0.719512
44,Maharashtra,Thane,400605,2025-03,0.0,0.0,0.0,314.0,2814.0,794.0,...,0.0,6050.0,0.816725,False,False,0.755950,False,0.756219,0.756219,0.715960
45,Maharashtra,Thane,400605,2025-04,0.0,0.0,0.0,0.0,0.0,1068.0,...,0.0,3154.0,0.661173,False,False,2086.000000,True,None,None,0.999065
46,Maharashtra,Thane,400605,2025-05,0.0,0.0,0.0,116.0,1111.0,764.0,...,0.0,3622.0,0.756831,False,False,1.466727,False,1.468047,1.468047,0.867196
47,Maharashtra,Thane,400605,2025-06,57.0,69.0,0.0,0.0,0.0,437.0,...,126.0,1818.0,0.689940,False,False,1255.000000,True,None,None,0.997717
48,Maharashtra,Thane,400605,2025-07,0.0,0.0,0.0,0.0,0.0,683.0,...,0.0,2250.0,0.696135,False,False,1567.000000,True,None,None,0.998538
49,Maharashtra,Thane,400605,2025-08,0.0,0.0,0.0,0.0,0.0,477.0,...,0.0,1595.0,0.700501,False,False,1118.000000,True,None,None,0.997908

In [85]:
m['CBCR'].describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9])

count    982.000000
mean       0.790433
std        0.279351
min        0.000000
10%        0.461011
25%        0.759836
50%        0.888889
75%        0.971218
90%        0.996275
max        0.999503
Name: CBCR, dtype: float64

In [87]:
# summarize how each PIN behaves overall.
cbcr_pin = (
    m.groupby('pincode')
     .agg(
         months_total=('month', 'nunique'),
         mean_CBCR=('CBCR', 'mean'),
         median_CBCR=('CBCR', 'median')
     )
     .reset_index()
)

cbcr_pin.head(50)

    pincode  months_total  mean_CBCR  median_CBCR
0    400601            11   0.842027     0.905109
1    400602            11   0.863107     0.924399
2    400603            11   0.953061     0.966667
3    400604            11   0.925556     0.935342
4    400605            11   0.888354     0.897677
5    400606            11   0.900249     0.927222
6    400607            11   0.857868     0.887168
7    400608            11   0.863983     0.905556
8    400610            11   0.851607     0.924870
9    400612            11   0.764564     0.752700
10   400614            11   0.904469     0.890110
11   400615            11   0.877471     0.855072
12   400701            10   0.902640     0.887961
13   400703            10   0.918893     0.937874
14   400705            11   0.908304     0.921642
15   400706            11   0.824816     0.834992
16   400708            11   0.900900     0.900000
17   400709            11   0.855771     0.918854
18   400710            10   0.923184     0.931116
19   401101            11   0.922293     0.926509
20   401102            10   0.819630     0.881538
21   401103             9   0.505556     0.500000
22   401104             9   0.514815     0.500000
23   401105            11   0.843249     0.901961
24   401106            11   0.867042     0.849673
25   401107            11   0.692157     0.797647
26   401201            11   0.929538     0.961538
27   401202            11   0.854820     0.888889
28   401203            11   0.941428     0.941176
29   401204            10   0.908519     0.923684
30   401206             9   0.800287     0.800000
31   401207            10   0.875191     0.923077
32   401208            10   0.885420     0.913984
33   401209            10   0.920218     0.933652
34   401301            11   0.853824     0.933333
35   401302             9   0.821143     0.857143
36   401303            11   0.939508     0.961538
37   401304            10   0.744306     0.861111
38   401305            11   0.933418     0.977273
39   401401             9   0.364815     0.400000
40   401402             9   0.490278     0.666667
41   401403             9   0.639835     0.714286
42   401404            11   0.879171     0.888889
43   401405             9   0.418519     0.500000
44   401501            11   0.873094     0.909091
45   401502             9   0.717460     0.800000
46   401503             9   0.461905     0.500000
47   401504            10   0.791940     0.892045
48   401506             9   0.487037     0.666667
49   401601             9   0.664590     0.750000

In [89]:
cbcr_cutoff = cbcr_pin['mean_CBCR'].quantile(0.25)
cbcr_cutoff

0.7614666461237024

In [90]:
cbcr_pin['low_CBCR'] = cbcr_pin['mean_CBCR'] <= cbcr_cutoff

In [93]:
cbcr_pin.head()

   pincode  months_total  mean_CBCR  median_CBCR  low_CBCR
0   400601            11   0.842027     0.905109     False
1   400602            11   0.863107     0.924399     False
2   400603            11   0.953061     0.966667     False
3   400604            11   0.925556     0.935342     False
4   400605            11   0.888354     0.897677     False

In [94]:
# merging into pin_summary
pin_summary = pin_summary.merge(
    cbcr_pin[['pincode', 'mean_CBCR', 'median_CBCR', 'low_CBCR']],
    on='pincode',
    how='left'
)

In [96]:
pin_summary.shape

(96, 16)

# Enrollment Saturation

### What this metric answers 
### In this PIN and month, how much Aadhaar activity is still about creating new Aadhaar numbers versus just maintaining existing ones?

### Low value → area is already enrolled (saturated)
### High value → area still needs enrolment capacity

# Formula:
### 1) New_enrol_pin (all the enrolments in a particular month)
### 2) Total_txn_pin (all the transactions in that month which include new_enrol_pin, all biometric updates and all demographic updates)
### ENROLMENT SATURATION = NEW_ENROL_PIN / (TOTAL_TXN_PIN + 1)

In [99]:
m.columns

Index(['state', 'district', 'pincode', 'month', 'age_0_5', 'age_5_17',
       'age_18_greater', 'demo_age_5_17', 'demo_age_17_', 'bio_age_5_17',
       'bio_age_17_', 'new_enrol', 'total_txn', 'ICI', 'ici_top_10pct',
       'ici_top_25pct', 'BDR', 'biometric_only', 'BDR_valid', 'BDR_capped',
       'CBCR'],
      dtype='object')

In [100]:
# computing total aadhar transactions 

m['total_updates'] = (
    m['demo_age_5_17'] +
    m['demo_age_17_'] +
    m['bio_age_5_17'] +
    m['bio_age_17_']
)

m['total_txn'] = m['new_enrol'] + m['total_updates']

In [103]:
# computing the enrolment saturation per month 
m['enrol_sat'] = m['new_enrol'] / (m['total_txn'] + 1)

In [105]:
m.drop(columns="ENROL_SAT",inplace=True)

In [106]:
m

,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,...,ICI,ici_top_10pct,ici_top_25pct,BDR,biometric_only,BDR_valid,BDR_capped,CBCR,total_updates,enrol_sat
0,Maharashtra,Thane,400601,2025-03,0.0,0.0,0.0,99.0,1058.0,0.0,...,0.913644,False,True,0.000000,False,0.0,0.0,0.000000,1157.0,0.000000
1,Maharashtra,Thane,400601,2025-04,0.0,0.0,0.0,104.0,783.0,393.0,...,0.764205,False,False,1.059949,False,1.061303,1.061303,0.789157,2111.0,0.000000
2,Maharashtra,Thane,400601,2025-05,80.0,30.0,14.0,0.0,0.0,575.0,...,0.615807,False,False,1122.000000,True,None,None,0.998264,1697.0,0.068057
3,Maharashtra,Thane,400601,2025-06,53.0,33.0,1.0,0.0,0.0,165.0,...,0.725894,False,False,670.000000,True,None,None,0.993976,835.0,0.094258
4,Maharashtra,Thane,400601,2025-07,0.0,0.0,0.0,0.0,0.0,407.0,...,0.690909,False,False,912.000000,True,None,None,0.997549,1319.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
977,Maharashtra,Thane,421605,2025-09,105.0,78.0,0.0,51.0,440.0,496.0,...,0.554268,False,False,1.063492,False,1.065909,1.065909,0.905109,1456.0,0.111585
978,Maharashtra,Thane,421605,2025-10,60.0,33.0,0.0,28.0,422.0,344.0,...,0.661091,False,False,1.151300,False,1.154028,1.154028,0.922252,1281.0,0.067636
979,Maharashtra,Thane,421605,2025-11,74.0,44.0,1.0,104.0,1219.0,363.0,...,0.755620,False,False,0.488525,False,0.488925,0.488925,0.775641,2282.0,0.049542
980,Maharashtra,Thane,421605,2025-12,32.0,19.0,2.0,127.0,1267.0,411.0,...,0.765173,False,False,0.522082,False,0.522494,0.522494,0.762523,2467.0,0.021023
981,Maharashtra,Thane,421605,2026-01,16.0,8.0,0.0,4.0,74.0,34.0,...,0.663102,False,False,0.666667,False,0.675676,0.675676,0.871795,162.0,0.128342

In [109]:
m['enrol_sat'].describe(percentiles=[0.1, 0.25, 0.5, 0.75, 0.9])

count    982.000000
mean       0.031097
std        0.045696
min        0.000000
10%        0.000000
25%        0.000000
50%        0.012618
75%        0.048377
90%        0.085098
max        0.393426
Name: enrol_sat, dtype: float64

In [110]:
# calculate the overall pin behaviour for enrolment 

enrol_pin = (
    m.groupby('pincode')
     .agg(
         months_total=('month', 'nunique'),
         mean_ENROL_SAT=('enrol_sat', 'mean'),
         median_ENROL_SAT=('enrol_sat', 'median'),
         mean_new_enrol=('new_enrol', 'mean'),
         mean_total_updates=('total_updates', 'mean')
     )
     .reset_index()
)

In [111]:
enrol_pin.head()

,pincode,months_total,mean_ENROL_SAT,median_ENROL_SAT,mean_new_enrol,mean_total_updates
0,400601,11,0.041322,0.045302,79.272727,1976.000000
1,400602,11,0.023579,0.033360,15.818182,574.181818
2,400603,11,0.020997,0.020561,13.909091,698.727273
3,400604,11,0.044422,0.022979,136.181818,3189.090909
4,400605,11,0.033496,0.025631,77.454545,3180.909091

In [113]:
sat_cutoff = enrol_pin['median_ENROL_SAT'].quantile(0.25)
sat_cutoff

0.007101065727438615

In [114]:
enrol_pin['is_saturated'] = enrol_pin['median_ENROL_SAT'] <= sat_cutoff

In [116]:
enrol_pin.head(50)

,pincode,months_total,mean_ENROL_SAT,median_ENROL_SAT,mean_new_enrol,mean_total_updates,is_saturated
0,400601,11,0.041322,0.045302,79.272727,1976.000000,False
1,400602,11,0.023579,0.033360,15.818182,574.181818,False
2,400603,11,0.020997,0.020561,13.909091,698.727273,False
3,400604,11,0.044422,0.022979,136.181818,3189.090909,False
4,400605,11,0.033496,0.025631,77.454545,3180.909091,False
5,400606,11,0.022986,0.022732,54.909091,2381.272727,False
6,400607,11,0.037284,0.039263,76.090909,1865.454545,False
7,400608,11,0.036963,0.028761,13.272727,380.000000,False
8,400610,11,0.024343,0.034115,20.636364,721.636364,False
9,400612,11,0.064679,0.056814,657.090909,10622.818182,False
10,400614,11,0.033644,0.036634,18.909091,552.181818,False
11,400615,11,0.031020,0.020753,46.727273,1398.454545,False
12,400701,10,0.064113,0.040305,111.300000,2096.000000,False
13,400703,10,0.041136,0.029476,63.400000,1758.700000,False
14,400705,11,0.054745,0.034913,51.545455,1113.000000,False
15,400706,11,0.035744,0.037127,90.181818,2269.000000,False
16,400708,11,0.044707,0.037731,109.272727,2819.272727,False
17,400709,11,0.044318,0.024791,88.909091,1995.363636,False
18,400710,10,0.023101,0.021937,4.000000,178.700000,False
19,401101,11,0.025590,0.033035,45.818182,1572.000000,False
20,401102,10,0.012966,0.007762,4.800000,393.900000,False
21,401103,9,0.021447,0.001332,3.222222,264.222222,True
22,401104,9,0.033861,0.017544,1.222222,49.444444,False
23,401105,11,0.032281,0.026657,72.090909,2204.636364,False
24,401106,11,0.036434,0.018917,14.636364,511.181818,False
25,401107,11,0.066026,0.061328,499.454545,6558.545455,False
26,401201,11,0.021782,0.008006,9.636364,513.636364,False
27,401202,11,0.020144,0.002947,9.818182,451.545455,True
28,401203,11,0.023225,0.019397,11.090909,434.727273,False
29,401204,10,0.025781,0.009707,5.500000,277.000000,False
30,401206,9,0.022622,0.000000,3.777778,102.444444,True
31,401207,10,0.016846,0.005698,2.600000,139.400000,True
32,401208,10,0.038316,0.031894,28.300000,745.000000,False
33,401209,10,0.031142,0.030028,37.500000,1320.100000,False
34,401301,11,0.019389,0.006834,4.727273,229.363636,True
35,401302,9,0.039498,0.006993,8.111111,179.777778,True
36,401303,11,0.019546,0.010590,12.090909,702.000000,False
37,401304,10,0.028620,0.020998,2.900000,107.900000,False
38,401305,11,0.020505,0.014943,17.454545,930.454545,False
39,401401,9,0.011477,0.000000,1.222222,102.888889,True
40,401402,9,0.022134,0.008163,1.444444,77.666667,False
41,401403,9,0.007073,0.001096,4.444444,542.111111,True
42,401404,11,0.017096,0.007383,11.000000,748.545455,False
43,401405,9,0.016116,0.000000,1.222222,121.111111,True
44,401501,11,0.024830,0.019183,18.909091,775.181818,False
45,401502,9,0.011446,0.000000,1.333333,136.000000,True
46,401503,9,0.009410,0.000000,1.333333,148.444444,True
47,401504,10,0.013604,0.011810,2.100000,145.400000,False
48,401506,9,0.024907,0.000000,1.111111,41.777778,True
49,401601,9,0.007916,0.003279,1.555556,149.777778,True

In [117]:
pin_summary = pin_summary.merge(
    enrol_pin[['pincode', 'mean_ENROL_SAT', 'median_ENROL_SAT', 'is_saturated']],
    on='pincode',
    how='left'
)

In [118]:
pin_summary.head()

,pincode,months_total_x,top10_count,top25_count,top10_frac,top25_frac,months_total_y,biometric_only_count,biometric_only_fraction,median_BDR,mean_BDR,high_biometric_only,high_BDR,mean_CBCR,median_CBCR,low_CBCR,mean_ENROL_SAT,median_ENROL_SAT,is_saturated
0,400601,11,0,1,0.0,0.090909,11,4,0.363636,1.061303,1.024093,False,False,0.842027,0.905109,False,0.041322,0.045302,False
1,400602,11,0,1,0.0,0.090909,11,5,0.454545,0.892646,0.821139,True,False,0.863107,0.924399,False,0.023579,0.033360,False
2,400603,11,0,0,0.0,0.000000,11,5,0.454545,1.674895,1.81907,True,True,0.953061,0.966667,False,0.020997,0.020561,False
3,400604,11,0,0,0.0,0.000000,11,5,0.454545,1.262306,1.307597,True,False,0.925556,0.935342,False,0.044422,0.022979,False
4,400605,11,0,0,0.0,0.000000,11,4,0.363636,1.011805,1.026834,False,False,0.888354,0.897677,False,0.033496,0.025631,False

In [123]:
pin_summary['months_total'] = pin_summary['months_total_x']
pin_summary = pin_summary.drop(columns=['months_total_x', 'months_total_y'])

In [124]:
pin_summary

,pincode,top10_count,top25_count,top10_frac,top25_frac,biometric_only_count,biometric_only_fraction,median_BDR,mean_BDR,high_biometric_only,high_BDR,mean_CBCR,median_CBCR,low_CBCR,mean_ENROL_SAT,median_ENROL_SAT,is_saturated,months_total
0,400601,0,1,0.000000,0.090909,4,0.363636,1.061303,1.024093,False,False,0.842027,0.905109,False,0.041322,0.045302,False,11
1,400602,0,1,0.000000,0.090909,5,0.454545,0.892646,0.821139,True,False,0.863107,0.924399,False,0.023579,0.033360,False,11
2,400603,0,0,0.000000,0.000000,5,0.454545,1.674895,1.81907,True,True,0.953061,0.966667,False,0.020997,0.020561,False,11
3,400604,0,0,0.000000,0.000000,5,0.454545,1.262306,1.307597,True,False,0.925556,0.935342,False,0.044422,0.022979,False,11
4,400605,0,0,0.000000,0.000000,4,0.363636,1.011805,1.026834,False,False,0.888354,0.897677,False,0.033496,0.025631,False,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,421601,0,0,0.000000,0.000000,5,0.454545,0.470648,0.496555,True,False,0.932688,0.938859,False,0.036239,0.018301,False,11
92,421602,0,0,0.000000,0.000000,6,0.545455,1.058824,1.439332,True,False,0.958141,0.989796,False,0.046140,0.026701,False,11
93,421603,0,0,0.000000,0.000000,6,0.545455,0.4,0.665,True,False,0.844332,0.933333,False,0.024726,0.000000,True,11
94,421604,3,9,0.333333,1.000000,4,0.444444,2.0,1.68405,False,True,0.166667,0.000000,True,0.009575,0.005495,True,9
95,421605,0,1,0.000000,0.090909,5,0.454545,0.599085,0.651172,True,False,0.836860,0.922252,False,0.041835,0.021023,False,11

In [125]:
pin_summary.to_csv(
    "D:/UIDAI HACKATHON/UIDAI-Hackathon/data/processed/pin_summary.csv",
    index=False
)

In [126]:
m.head()

,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,...,ICI,ici_top_10pct,ici_top_25pct,BDR,biometric_only,BDR_valid,BDR_capped,CBCR,total_updates,enrol_sat
0,Maharashtra,Thane,400601,2025-03,0.0,0.0,0.0,99.0,1058.0,0.0,...,0.913644,False,True,0.000000,False,0.0,0.0,0.000000,1157.0,0.000000
1,Maharashtra,Thane,400601,2025-04,0.0,0.0,0.0,104.0,783.0,393.0,...,0.764205,False,False,1.059949,False,1.061303,1.061303,0.789157,2111.0,0.000000
2,Maharashtra,Thane,400601,2025-05,80.0,30.0,14.0,0.0,0.0,575.0,...,0.615807,False,False,1122.000000,True,None,None,0.998264,1697.0,0.068057
3,Maharashtra,Thane,400601,2025-06,53.0,33.0,1.0,0.0,0.0,165.0,...,0.725894,False,False,670.000000,True,None,None,0.993976,835.0,0.094258
4,Maharashtra,Thane,400601,2025-07,0.0,0.0,0.0,0.0,0.0,407.0,...,0.690909,False,False,912.000000,True,None,None,0.997549,1319.0,0.000000

In [127]:
m.columns

Index(['state', 'district', 'pincode', 'month', 'age_0_5', 'age_5_17',
       'age_18_greater', 'demo_age_5_17', 'demo_age_17_', 'bio_age_5_17',
       'bio_age_17_', 'new_enrol', 'total_txn', 'ICI', 'ici_top_10pct',
       'ici_top_25pct', 'BDR', 'biometric_only', 'BDR_valid', 'BDR_capped',
       'CBCR', 'total_updates', 'enrol_sat'],
      dtype='object')

In [128]:
m.head()

,state,district,pincode,month,age_0_5,age_5_17,age_18_greater,demo_age_5_17,demo_age_17_,bio_age_5_17,...,ICI,ici_top_10pct,ici_top_25pct,BDR,biometric_only,BDR_valid,BDR_capped,CBCR,total_updates,enrol_sat
0,Maharashtra,Thane,400601,2025-03,0.0,0.0,0.0,99.0,1058.0,0.0,...,0.913644,False,True,0.000000,False,0.0,0.0,0.000000,1157.0,0.000000
1,Maharashtra,Thane,400601,2025-04,0.0,0.0,0.0,104.0,783.0,393.0,...,0.764205,False,False,1.059949,False,1.061303,1.061303,0.789157,2111.0,0.000000
2,Maharashtra,Thane,400601,2025-05,80.0,30.0,14.0,0.0,0.0,575.0,...,0.615807,False,False,1122.000000,True,None,None,0.998264,1697.0,0.068057
3,Maharashtra,Thane,400601,2025-06,53.0,33.0,1.0,0.0,0.0,165.0,...,0.725894,False,False,670.000000,True,None,None,0.993976,835.0,0.094258
4,Maharashtra,Thane,400601,2025-07,0.0,0.0,0.0,0.0,0.0,407.0,...,0.690909,False,False,912.000000,True,None,None,0.997549,1319.0,0.000000